WebProje/WebProje/Controllers/IlanVersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class IlanVersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: IlanVers
        [Authorize(Roles = "admin")]

        public ActionResult Index(string siralama , string arama )
        {
            HttpContext.Session["csayfa"] = menusecenekler.yurtlar;

            ViewBag.NameSortParm = string.IsNullOrEmpty(siralama) ? "KurumAdi_azalan" : "";
            ViewBag.DateSortParm = siralama == "tarih_artan" ? "tarih_azalan" : "tarih_artan";





            var ilanlar = from s in db.IlanVers
                          select s;


            //arama---
            if(!String.IsNullOrEmpty(arama))
            {
                ilanlar = ilanlar.Where(s => s.KurumAdi.ToUpper().Contains(arama.ToUpper())
                      || s.KisiAdi.ToUpper().Contains(arama.ToUpper()));
            }
            //--------

            //siralama---
            switch(siralama)
            {
                case  "KurumAdi_azalan":
                    ilanlar = ilanlar.OrderByDescending(s => s.KurumAdi);
                    break;
                case "tarih_artan":
                    ilanlar = ilanlar.OrderBy(s => s.Tarih);
                    break;
                case "tarih_azalan":
                    ilanlar = ilanlar.OrderByDescending(s => s.Tarih);
                    break;
                default:
                    ilanlar = ilanlar.OrderBy(s => s.KurumAdi);
                    break;

            }
            //------------



            return View(ilanlar.ToList());
        }

        // GET: IlanVers/Details/5
        [Authorize]

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IlanVer ilanVer = db.IlanVers.Find(id);
            if (ilanVer == null)
            {
                return HttpNotFound();
            }
            return View(ilanVer);
        }
        [Authorize(Roles = "admin,sahip")]

        // GET: IlanVers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: IlanVers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "admin,sahip")]

        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IlanTipi,Adres,Telefon,WebSitesi,KurumAdi,KisiAdi,Fotograf1,Fotograf2,Fotograf3,Aciklamalar")]  IlanModel ilanVer, HttpPostedFileBase Foto1, HttpPostedFileBase Foto2, HttpPostedFileBase Foto3)
        {
            if (ModelState.IsValid)
            {
                ilanVer.Tarih = System.DateTime.Now;
                string DosyaAdi = Guid.NewGuid().ToString().Replace('-', '1');// sunucumuzda bulunmayan rasgele bir string atıyor aralardaki - leri herhangi bir karakterle değiştiriyoruz
                string uzanti = System.IO.Path.GetExtension(Foto1.FileName);
                string veri_yolu = "~/Content/images/" + DosyaAdi + uzanti;
                Foto1.SaveAs(Server.MapPath(veri_yolu));
                string URL1 = "/Content/images/" + DosyaAdi + uzanti;// başında ~ yok bunu ekleyeceksin veritabanına

                DosyaAdi = Guid.NewGuid().ToString().Replace('-', '1');// sunucumuzda bulunmayan rasgele bir string atıyor aralardaki - leri herhangi bir karakterle değiştiriyoruz
                uzanti = System.IO.Path.GetExtension(Foto2.FileName);
                veri_yolu = "~/Content/images/" + DosyaAdi + uzanti;
                Foto2.SaveAs(Server.MapPath(veri_yolu));
                string URL2 = "/Content/images/" + DosyaAdi + uzanti;// başında ~ yok bunu ekleyeceksin veritabanına

                DosyaAdi = Guid.NewGuid().ToString().Replace('-', '1');// sunucumuzda bulunmayan rasgele bir string atıyor aralardaki - leri herhangi bir karakterle değiştiriyoruz
                uzanti = System.IO.Path.GetExtension(Foto3.FileName);
               veri_yolu = "~/Content/images/" + DosyaAdi + uzanti;
                Foto3.SaveAs(Server.MapPath(veri_yolu));
                string URL3 = "/Content/images/" + DosyaAdi + uzanti;// başında ~ yok bunu ekleyeceksin veritabanına

                string id = User.Identity.GetUserId();
                var kullanici = db.Users.Where(x => x.Id == id).SingleOrDefault();
                db.Users.Where(x => x.Id == id).SingleOrDefault();

                var user = new IlanVer { ID = ilanVer.ID, IlanTipi = ilanVer.IlanTipi, Adres = ilanVer.Adres, Tarih = ilanVer.Tarih, Telefon = ilanVer.Telefon, WebSitesi = ilanVer.WebSitesi, KurumAdi = ilanVer.KurumAdi, KisiAdi = ilanVer.KisiAdi, Fotograf1 = URL1, Fotograf2 = URL2, Fotograf3 = URL3, Aciklamalar = ilanVer.Aciklamalar, Kullanicilar = db.Users.Where(x => x.Id == id).SingleOrDefault() };



                db.IlanVers.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(ilanVer);
        }


































        // GET: IlanVers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IlanVer ilanVer = db.IlanVers.Find(id);
            if (ilanVer == null)
            {
                return HttpNotFound();
            }
            return View(ilanVer);
        }

        // POST: IlanVers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IlanTipi,Adres,Tarih,Telefon,WebSitesi,KurumAdi,KisiAdi,Fotograf1,Fotograf2,Fotograf3,Aciklamalar")] IlanVer ilanVer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ilanVer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ilanVer);
        }

        // GET: IlanVers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IlanVer ilanVer = db.IlanVers.Find(id);
            if (ilanVer == null)
            {
                return HttpNotFound();
            }
            return View(ilanVer);
        }

        // POST: IlanVers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IlanVer ilanVer = db.IlanVers.Find(id);
            db.IlanVers.Remove(ilanVer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebProje/WebProje/Views/IlanVers/Create.cshtml
@model WebProje.Models.IlanModel
@*//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Resim boşsa veya Büyükse Hata veriyor !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*@

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-6 animate-box">
    <h3 style="text-align:center">İlan Ver</h3>
@using (Html.BeginForm("Create", "IlanVers", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

      <div class="row form-group">
            <div class="col-md-6">

                @Html.LabelFor(model => model.KisiAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.KisiAdi, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.KisiAdi, "", new { @class = "text-danger" })

                </div>
            <div class="col-md-6" >
                @Html.LabelFor(model => model.KurumAdi, htmlAttributes: new { @class = "control-label col-md-2" })




                @Html.EditorFor(model => model.KurumAdi, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.KurumAdi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-12">


                @Html.LabelFor(model => model.IlanTipi, htmlAttributes: new { @class = "control-label col-md-2" })

                @Html.DropDownListFor(model => model.IlanTipi,  new SelectListItem[]{
                new SelectListItem() {Text = "Yurt", Value="Yurt"},
                new SelectListItem() {Text = "Apart", Value="Apart"}},new { @class = "form-control", required = "required" })
                @*@Html.EditorFor(model => model.IlanTipi, new { htmlAttributes = new { @class = "form-control", required = "required" } })*@
                @Html.ValidationMessageFor(model => model.IlanTipi, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.WebSitesi, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.WebSitesi, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.WebSitesi, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row form-group">
            <div class="col-md-12">
           @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-2" })
            @*@Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control", required = "required" } })*@
                @*@Html.TextAreaFor(model => model.Adres, new { @class = "form-control text-box single-line", rows = "5", required = "required" })*@
                @Html.DropDownListFor(model => model.Adres, new SelectListItem[]{
                new SelectListItem() {Text = "Adapazarı", Value="Adapazarı"},
                new SelectListItem() {Text = "Arifiye", Value="Arifiye"},
                new SelectListItem() {Text = "Hendek", Value="Hendek"},
                new SelectListItem() {Text = "Karasu", Value="Karasu"},
                new SelectListItem() {Text = "Sapanca", Value="Sapanca"},
                new SelectListItem() {Text = "Serdivan", Value="Serdivan"}}, new { @class = "form-control", required = "required" })
            @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
        </div>
        </div>

        <div class="row form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Aciklamalar, htmlAttributes: new { @class = "control-label col-md-2" })
                @*@Html.TextAreaFor(model => model.Aciklamalar, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.TextAreaFor(model => model.Aciklamalar, new { @class = "form-control text-box single-line", @placeholder = "Ek özelikleri yazınız Örn:Havuz", rows = "5", required = "required" })
                    @Html.ValidationMessageFor(model => model.Aciklamalar, "", new { @class = "text-danger" })
                </div>
        </div>


        <div class="row form-group">
            <div class="col-md-12">
            @Html.LabelFor(m => m.Foto1, new { @class = "col-md-2 control-label" })
            @Html.TextBoxFor(m => m.Foto1, new { @class = "form-control", placeholder = "Resim Yolu", type = "file", required = "required" })
                @Html.ValidationMessageFor(model => model.Foto1, "", new { @class = "text-danger" })


            </div>
        </div>


        <div class="row form-group">
            <div class="col-md-12">
            @Html.LabelFor(m => m.Foto2, new { @class = "col-md-2 control-label" })
            @Html.TextBoxFor(m => m.Foto2, new { @class = "form-control", placeholder = "Resim Yolu", type = "file", required = "required" })
                @Html.ValidationMessageFor(model => model.Foto2, "", new { @class = "text-danger" })


            </div>
        </div>


        <div class="row form-group">
            <div class="col-md-12">
                @Html.LabelFor(m => m.Foto3, new { @class = "col-md-2 control-label" })
                @Html.TextBoxFor(m => m.Foto3, new { @class = "form-control", placeholder = "Resim Yolu", type = "file" , required = "required" })
                @Html.ValidationMessageFor(model => model.Foto3, "", new { @class = "text-danger" })


            </div>
        </div>





        <div class="form-group">
            <input type="submit" value="Yayınla" class="btn btn-primary"  style="margin-left:250px">
        </div>





}
</div>
			












@*<h2>Create</h2>

@using (Html.BeginForm("Create", "IlanVers", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>IlanVer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IlanTipi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IlanTipi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IlanTipi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
            </div>
        </div>*@


@*silinebilir............................................*@
        @*<div class="form-group">
                @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
                </div>
            </div>*@
@*silinebilir.............................................*@


        @*@*<div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebSitesi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebSitesi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WebSitesi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KurumAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KurumAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KurumAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KisiAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KisiAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KisiAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Foto1, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Foto1, new { @class = "form-control", placeholder = "Resim Yolu", type = "file" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Foto2, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Foto2, new { @class = "form-control", placeholder = "Resim Yolu", type = "file" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Foto3, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Foto3, new { @class = "form-control", placeholder = "Resim Yolu", type = "file" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Aciklamalar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aciklamalar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aciklamalar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

WebProje/WebProje/Views/IlanVers/Delete.cshtml
@model WebProje.Models.IlanVer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IlanVer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IlanTipi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IlanTipi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebSitesi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebSitesi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KurumAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KurumAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KisiAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KisiAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fotograf1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fotograf1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fotograf2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fotograf2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fotograf3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fotograf3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aciklamalar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklamalar)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebProje/WebProje/Views/IlanVers/Details.cshtml
@model WebProje.Models.IlanVer
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Details</h2>

<div>
    <h4>IlanVer</h4>
    <hr />
    <dl class="dl-horizontal">*@
        @*<dt>
                @Html.DisplayNameFor(model => model.IlanTipi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IlanTipi)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.Adres)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adres)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.Tarih)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tarih)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.Telefon)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Telefon)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.WebSitesi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WebSitesi)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.KurumAdi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KurumAdi)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.KisiAdi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KisiAdi)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.Fotograf1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fotograf1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Fotograf2)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fotograf2)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Fotograf3)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fotograf3)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.Aciklamalar)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Aciklamalar)
            </dd>*@

    @*</dl>
</div>*@
@*@if(Model.Kullanicilar.Id==User.Identity.GetUserId())
    {

    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
    }*@


<div id="fh5co-pricing">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">

                <h2>İLAN DETAYLARI</h2>
            </div>
        </div>
        <div class="row">
            <div class="pricing">

                <div class="col-md-3 animate-box" style="width:100% ; height:100% ">
                    <div class="price-box">
                        <h2 class="pricing-plan">@Html.DisplayFor(model => model.KurumAdi)</h2>
                        <ul class="classes">


                            <li>@Html.DisplayNameFor(model => model.IlanTipi)</li>
                            <li class="color">@Html.DisplayFor(model => model.IlanTipi)</li>

                            <li>@Html.DisplayNameFor(model => model.Tarih)</li>
                            <li class="color">@Html.DisplayFor(model => model.Tarih)</li>

                            <li>@Html.DisplayNameFor(model => model.Telefon)</li>
                            <li class="color">@Html.DisplayFor(model => model.Telefon)</li>

                            <li>@Html.DisplayNameFor(model => model.KisiAdi)</li>
                            <li class="color">@Html.DisplayFor(model => model.KisiAdi)</li>

                            <li>@Html.DisplayNameFor(model => model.WebSitesi)</li>
                            <li class="color">@Html.DisplayFor(model => model.WebSitesi)</li>

                            <li>@Html.DisplayNameFor(model => model.Adres)</li>
                            <li class="color">@Html.DisplayFor(model => model.Adres)</li>

                            <li>@Html.DisplayNameFor(model => model.Aciklamalar)</li>
                            <li class="color">@Html.DisplayFor(model => model.Aciklamalar)</li>
                        </ul>


                        <div class="row animate-box"  height="40%" width="40%">
                            <div class="owl-carousel owl-carousel-fullwidth">

                                <div class="item">
                                    <div class="testimony-slide active text-center">
                                        <figure>
                                            <div class="price"><img src="@Html.DisplayFor(model => model.Fotograf1)" alt="user"></div>

                                        </figure>

                                    </div>
                                </div>
                                <div class="item">
                                    <div class="testimony-slide active text-center">
                                        <figure>
                                            <div class="price"><img src="@Html.DisplayFor(model => model.Fotograf2)" alt="user" ></div>

                                        </figure>

                                    </div>
                                </div>
                                <div class="item">
                                    <div class="testimony-slide active text-center">
                                        <figure>
                                            <div class="price"><img src="@Html.DisplayFor(model => model.Fotograf3)" alt="user" ></div>

                                        </figure>

                                    </div>
                                </div>

                            </div>
                        </div>
                        @if (Model.Kullanicilar.Id == User.Identity.GetUserId())
                        {

                            <p>
                                @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) 
                            </p>
                        }


                    </div>

                </div>
            </div>
        </div>

    </div>
</div>

@*<li>:@item.WebSitesi</li>
                                    <li class="color">@item.Adres</li>
                                    <div class="price"><img src="@item.Fotograf1" alt="user" height="250" width="200"></div>
                                    <div class="price"><img src="@item.Fotograf1" alt="user" height="250" width="200"></div>
                                    <div class="price"><img src="@item.Fotograf1" alt="user" height="250" width="200"></div>


                                </ul>

                                <a href="@Url.Action("Details","IlanVers", new { id = item.ID })" class="btn btn-select-plan btn-sm">İlanı İncele</a>

                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>*@