WebProje/WebProje/Controllers/AdminAnaSayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebProje.Controllers
{
    public class AdminAnaSayfaController : Controller
    {
        // GET: AdminAnaSayfa
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebProje/WebProje/Controllers/ArkadasController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class ArkadasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Arkadas
        [Authorize(Roles = "admin")]
        public ActionResult Index(string siralama, string arama)
        {
            HttpContext.Session["csayfa"] = menusecenekler.arkadas;
            ViewBag.DateSortParm = siralama == "tarih_artan" ? "tarih_azalan" : "tarih_artan";

            var arkadaslar = from s in db.Arkadas
                          select s;
            if (!String.IsNullOrEmpty(arama))
            {
               arkadaslar = arkadaslar.Where(s => s.ArkadasDetay.ToUpper().Contains(arama.ToUpper()));
            }
            switch (siralama)
            {
                
                case "tarih_artan":
                    arkadaslar = arkadaslar.OrderBy(s => s.Tarih);
                    break;
                case "tarih_azalan":
                    arkadaslar = arkadaslar.OrderByDescending(s => s.Tarih);
                    break;
              

            }







            return View(arkadaslar.ToList());
        }

        [Authorize(Roles = "admin,ogrenci")]

        // GET: Arkadas/Details/5
        public ActionResult Details(int? id)
        {
            HttpContext.Session["csayfa"] = menusecenekler.arkadas;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arkadas arkadas = db.Arkadas.Find(id);
            if (arkadas == null)
            {
                return HttpNotFound();
            }
            return View(arkadas);
        }

        // GET: Arkadas/Create
        [Authorize(Roles = "admin,ogrenci")]

        public ActionResult Create()
        {
            HttpContext.Session["csayfa"] = menusecenekler.arkadas;

            return View();
        }

        // POST: Arkadas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,ogrenci")]

        public ActionResult Create([Bind(Include = "ID,ArkadasDetay")] Arkadas arkadas)
        {
            HttpContext.Session["csayfa"] = menusecenekler.arkadas;

            if (ModelState.IsValid)
            {
                arkadas.Tarih = System.DateTime.Now;

                string id = User.Identity.GetUserId();
                var kullanici = db.Users.Where(x => x.Id == id).SingleOrDefault();
                arkadas.Kullanicilar = db.Users.Where(x => x.Id == id).SingleOrDefault();
                db.Arkadas.Add(arkadas);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(arkadas);
        }

        // GET: Arkadas/Edit/5
        [Authorize(Roles = "admin,ogrenci")]

        public ActionResult Edit(int? id)
        {
            HttpContext.Session["csayfa"] = menusecenekler.arkadas;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arkadas arkadas = db.Arkadas.Find(id);
            if (arkadas == null)
            {
                return HttpNotFound();
            }
            return View(arkadas);
        }

        // POST: Arkadas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,ogrenci")]

        public ActionResult Edit([Bind(Include = "ID,ArkadasDetay,Tarih")] Arkadas arkadas)
        {
            HttpContext.Session["csayfa"] = menusecenekler.arkadas;

            if (ModelState.IsValid)
            {
                db.Entry(arkadas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(arkadas);
        }

        // GET: Arkadas/Delete/5
        [Authorize(Roles = "admin,ogrenci")]

        [Authorize(Roles = "admin,ogrenci")]

        public ActionResult Delete(int? id)
        {
            HttpContext.Session["csayfa"] = menusecenekler.arkadas;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arkadas arkadas = db.Arkadas.Find(id);
            if (arkadas == null)
            {
                return HttpNotFound();
            }
            return View(arkadas);
        }

        // POST: Arkadas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,ogrenci")]

        public ActionResult DeleteConfirmed(int id)
        {
            HttpContext.Session["csayfa"] = menusecenekler.arkadas;

            Arkadas arkadas = db.Arkadas.Find(id);
            db.Arkadas.Remove(arkadas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebProje/WebProje/Controllers/YorumsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class YorumsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize(Roles = "admin")]

        // GET: Yorums
        public ActionResult Index(string siralama, string arama)
        {
            HttpContext.Session["csayfa"] = menusecenekler.yorumlar;

            // burada session atamadığın için anasayfa olarak algılıyor artık hmm anladım sağolasın kanka ne demek 
            ViewBag.DateSortParm = siralama == "tarih_artan" ? "tarih_azalan" : "tarih_artan";

            var yorumlar = from s in db.Yorums
                             select s;
            if (!String.IsNullOrEmpty(arama))
            {
                yorumlar = yorumlar.Where(s => s.Yorum1.ToUpper().Contains(arama.ToUpper()));
            }
            switch (siralama)
            {

                case "tarih_artan":
                    yorumlar = yorumlar.OrderBy(s => s.Tarih);
                    break;
                case "tarih_azalan":
                    yorumlar = yorumlar.OrderByDescending(s => s.Tarih);
                    break;


            }




            return View(yorumlar.ToList());
        }

        // GET: Yorums/Details/5
        [Authorize]

        public ActionResult Details(int? id)
        {
            HttpContext.Session["csayfa"] = menusecenekler.yorumlar;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yorum yorum = db.Yorums.Find(id);
            if (yorum == null)
            {
                return HttpNotFound();
            }
            return View(yorum);
        }

        // GET: Yorums/Create
        [Authorize]

        public ActionResult Create()
        {
            HttpContext.Session["csayfa"] = menusecenekler.yorumlar;

            return View();
        }

        // POST: Yorums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]

        public ActionResult Create([Bind(Include = "ID,Yorum1")] Yorum yorum)
        {
            HttpContext.Session["csayfa"] = menusecenekler.yorumlar;

            if (ModelState.IsValid)
            {
                yorum.Tarih = System.DateTime.Now;
                string id = User.Identity.GetUserId();
                var kullanici = db.Users.Where(x => x.Id == id).SingleOrDefault();
                yorum.Kullanicilar = db.Users.Where(x => x.Id == id).SingleOrDefault();

                db.Yorums.Add(yorum);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(yorum);
        }

        // GET: Yorums/Edit/5
        [Authorize]

        public ActionResult Edit(int? id)
        {
            HttpContext.Session["csayfa"] = menusecenekler.yorumlar;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yorum yorum = db.Yorums.Find(id);
            if (yorum == null)
            {
                return HttpNotFound();
            }
            return View(yorum);
        }

        // POST: Yorums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Yorum1,Tarih")] Yorum yorum)
        {
            HttpContext.Session["csayfa"] = menusecenekler.yorumlar;

            if (ModelState.IsValid)
            {
                db.Entry(yorum).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(yorum);
        }
        [Authorize]

        // GET: Yorums/Delete/5
        public ActionResult Delete(int? id)
        {
            HttpContext.Session["csayfa"] = menusecenekler.yorumlar;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yorum yorum = db.Yorums.Find(id);
            if (yorum == null)
            {
                return HttpNotFound();
            }
            return View(yorum);
        }

        // POST: Yorums/Delete/5
        [Authorize]

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HttpContext.Session["csayfa"] = menusecenekler.yorumlar;

            Yorum yorum = db.Yorums.Find(id);
            db.Yorums.Remove(yorum);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebProje/WebProje/Views/Shared/_ArkadasGoster.cshtml
@model  List<WebProje.Models.Arkadas>


<div id="fh5co-testimonial" class="fh5co-bg-section">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Son İlanlar</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="row animate-box">
                    <div class="owl-carousel owl-carousel-fullwidth">


                        @foreach (var item in Model)
                        {
                            <div class="item">
                                <div class="testimony-slide active text-center">
                                    <figure>
                                        <img src="@item.Kullanicilar.Resim" alt="user">
                                    </figure>
                                    <span>@item.Kullanicilar.Ad</span>
                                    <blockquote>
                                        <p>&ldquo; @item.ArkadasDetay &rdquo;</p>
                                    </blockquote>
                                </div>
                            </div>
                        }





                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebProje/WebProje/Views/Shared/_Layout.cshtml
@using WebProje.Models;    
<!DOCTYPE HTML>
    <html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>@ViewBag.Title &mdash; Sakarya'nın tüm yurt ve apartları burada</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Sakarya Ogrenci Ev ve Apartları" />
        <meta name="keywords" content="yurt,apart,sakarya,ogrenci,adapazari,serdivan,hendek,sapanca,ev" />
        <meta name="author" content="muratozdemir" />
        <!--
        //////////////////////////////////////////////////////

        Murat Özdemir
        DESIGNED & DEVELOPED by mrtzdmrr

        Website: 		mrtzdmrr.com
        Email: 			mrtzdmrr@gmail.com
        Instagram: 		mrtzdmrr
        Facebook: 		Murat Özdemir

        //////////////////////////////////////////////////////
         -->
        
        <!-- Facebook and Twitter integration -->
        <meta property="og:title" content="" />
        <meta property="og:image" content="" />
        <meta property="og:url" content="" />
        <meta property="og:site_name" content="" />
        <meta property="og:description" content="" />
        <meta name="twitter:title" content="" />
        <meta name="twitter:image" content="" />
        <meta name="twitter:url" content="" />
        <meta name="twitter:card" content="" />
        <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">

        @Styles.Render("~/Content/css")           @*css dosyaları eklenir*@
        @Scripts.Render("~/bundles/modernizr")    @*modernizr eklenir*@
    </head>
    <body>

        <div class="fh5co-loader"></div>

        <div id="page">
            <nav class="fh5co-nav" role="navigation">
                <div class="top">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 text-right">
                                <p class="num">GSM: +90 537 346 78 00</p>
                                <ul class="fh5co-social">
                                   <li>@Html.Partial("_LoginPartial")</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="top-menu">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-2">
                                <div id="fh5co-logo"><a href="@Url.Action("Index", "Home")">OGRENCISARAYI<span>.</span></a></div>
                            </div>
                            @{ 
                                menusecenekler csayfa = menusecenekler.anasayfa;
                                if (HttpContext.Current.Session["csayfa"] != null)
                                {
                                    csayfa = (menusecenekler)HttpContext.Current.Session["csayfa"]; /*menusecenekler.anasayfa; bunu yazmayı unutmulum sory*/
                                }
                                }
                            <div class="col-xs-10 text-right menu-1">
                                <ul>
                                    <li class="@Html.Raw(csayfa == menusecenekler.anasayfa ? "active" : "")">@Html.ActionLink(WebProje.Resources.LayoutTexts.anasayfa, "Index", "Home")</li>
                                    <li class="has-dropdown @Html.Raw(csayfa == menusecenekler.yurtlar ? "active" : "")">
                                        @Html.ActionLink(WebProje.Resources.LayoutTexts.yurtlar, "YurtBul", "Home")</a>
                                        <ul class="dropdown">
                                            <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.yurtbul, "YurtBul", "Home")</li>
                                            <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.ilanver, "Create", "IlanVers")</li>
                                         </ul>
                                    </li>
                                    <li class="has-dropdown  @Html.Raw(csayfa == menusecenekler.apartlar ? "active" : "")" >
                                        @Html.ActionLink(WebProje.Resources.LayoutTexts.apartlar, "ApartBul", "Home")</a>
                                        <ul class="dropdown">
                                            <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.ilanbul, "ApartBul", "Home")</li>
                                            <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.ilanver, "Create", "IlanVers")</li>
                                        </ul>
                                    </li>
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.arkadasedin, "Create", "Arkadas" ,null,new { @class = csayfa == menusecenekler.anasayfa ? "active" : "" })</li>
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.yorumlar, "Create", "Yorums",null, new { @class = csayfa == menusecenekler.apartlar ? "active" : "" })</li>
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.iletisim, "Contact", "Home",null, new { @class = csayfa == menusecenekler.apartlar ? "active" : "" })</li>
                                    <li>@Html.ActionLink("English", "Change", "Language", new { LanguageAbbrevation = "en" }, null)</li>
                                    <li>@Html.ActionLink("Türkçe", "Change", "Language", new { LanguageAbbrevation = "tr" }, null)</li>

                                </ul>
                            </div>
                        </div>

                    </div>
                </div>
              
            </nav>


            @RenderBody();



            <footer id="fh5co-footer" class="fh5co-bg" style="background-image: url(/images/img_bg_1.jpg);" role="contentinfo">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row row-pb-md">
                        <div class="col-md-4 fh5co-widget">
                            <h3>@WebProje.Resources.LayoutTexts.bizkimmiyiz</h3>
                            <p>@WebProje.Resources.LayoutTexts.bizsuan</p>
                            <p><a class="btn btn-primary" href="/Account/Register"> @WebProje.Resources.LayoutTexts.bizekatilin </a></p>
                        </div>
                        <div class="col-md-8">
                            <h3>@WebProje.Resources.LayoutTexts.hizmetler</h3>
                            <div class="col-md-4 col-sm-4 col-xs-6">
                                <ul class="fh5co-footer-links">
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.yurtbul, "YurtBul", "Home")</li>
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.apartbul, "ApartBul", "Home")</li>
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.arkadasbul, "Create", "Arkadas")</li>
                                </ul>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-6">
                                <ul class="fh5co-footer-links">
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.yurtilaniver, "Create", "IlanVers")</li>
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.apartilaniver, "Create", "IlanVers")</li>
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.arkadasilaniver, "Create", "Arkadas")</li>
                                </ul>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-6">
                                <ul class="fh5co-footer-links">
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.yorumlar, "Create", "Yorums")</li>
                                    <li>@Html.ActionLink(WebProje.Resources.LayoutTexts.iletisim, "Contact", "Home")</li>
                                   


                                    <li>@Html.ActionLink("Admin", "Index", "AdminAnaSayfa")</li>



                                   
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="row copyright">
                        <div class="col-md-12 text-center">
                            <p>
                                <small class="block">&copy; @DateTime.Now.Year ISTANBUL/TURKEY</small>
                                <small class="block">Designed by Murat Özdemir </small>
                            </p>
                            <p>
                                <ul class="fh5co-social-icons">
                                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                                    <li><a href="#"><i class="icon-instagram"></i></a></li>
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <div class="gototop js-top">
            <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
        </div>

      
        
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)


    </body>
</html>


   

WebProje/WebProje/Views/Shared/_YorumGoster.cshtml
@model  List<WebProje.Models.Yorum>


<div id="fh5co-testimonial" class="fh5co-bg-section">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>@WebProje.Resources.LayoutTexts.sonyorumlar</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="row animate-box">
                    <div class="owl-carousel owl-carousel-fullwidth">


                        @foreach (var item in Model)
                        {
                            <div class="item">
                                <div class="testimony-slide active text-center">
                                    <figure>
                                        <img src="@item.Kullanicilar.Resim" alt="user">
                                    </figure>
                                    <span>@item.Kullanicilar.Ad</span>
                                    <blockquote>
                                        <p>&ldquo; @item.Yorum1 &rdquo;</p>
                                    </blockquote>
                                </div>
                            </div>
                        }





                    </div>
                </div>
            </div>
        </div>
    </div>
</div>